modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="coordinatesdisplay" #mandatory
version="2.1.1" #mandatory
displayName="Coordinates Display" #mandatory
logoFile="icon.png" #optional
authors="Boxadactle" #optional
description='''

'''
[[dependencies.coordinatesdisplay]] #optional
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[40,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.coordinatesdisplay]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.coordinatesdisplay]]
    modId="cloth_config"
    mandatory=true
    versionRange="[6.1.57, 6.2.62]"
    side="CLIENT"
